export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const UNSET_PRODUCT_LOADING = "UNSET_PRODUCT_LOADING";
