export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const SET_CATEGORY_LOADING = "SET_CATEGORY_LOADING";
export const UNSET_CATEGORY_LOADING = "UNSET_CATEGORY_LOADING";
